import { dark } from '@clerk/themes';

export const clerkAppearance = {
  baseTheme: dark,
  variables: {
    colorPrimary: '#C71F37',
    colorBackground: '#1A1A1A',
    colorInputBackground: '#1A1A1A',
    colorInputText: '#F5F5F5',
    colorText: '#F5F5F5',
    colorTextSecondary: '#B8B9C3',
    colorTextOnPrimaryBackground: '#F5F5F5',
    colorDanger: '#EF4444',
    colorSuccess: '#10B981',
    colorNeutral: '#2A2A2A',
    borderRadius: '0.5rem',
  },
  layout: {
    socialButtonsPlacement: 'top',
    socialButtonsVariant: 'blockButton',
  },
  elements: {
    rootBox: 'mx-auto',
    card: 'bg-muted border border-border shadow-none',
    headerTitle: 'hidden',
    headerSubtitle: 'hidden',
    footer: 'bg-muted border-t border-border',
    footerAction: 'bg-muted',
    formButtonPrimary: 'bg-primary hover:bg-primary/90 text-white font-semibold',
    footerActionLink: 'text-primary hover:text-primary/80 font-medium',
    formFieldLabel: 'text-foreground font-medium mb-2',
    formFieldInput: 'bg-background border border-border text-foreground placeholder:text-muted-foreground focus:border-primary focus:ring-1 focus:ring-primary',
    formFieldInputShowPasswordButton: 'text-muted-foreground hover:text-foreground',
    identityPreviewText: 'text-foreground',
    identityPreviewEditButtonIcon: 'text-muted-foreground',
    formHeaderTitle: 'text-foreground',
    formHeaderSubtitle: 'text-muted-foreground',
    footerActionText: 'text-foreground',
    dividerLine: 'bg-border',
    dividerText: 'text-muted-foreground bg-muted px-2',
    socialButtonsBlockButton: 'bg-muted border border-border hover:bg-muted/60 hover:border-primary/50 text-foreground transition-all',
    socialButtonsBlockButtonText: 'text-foreground font-medium',
    socialButtonsIconButton: 'border-border',
    formFieldErrorText: 'text-red-400',
    formFieldSuccessText: 'text-green-400',
    otpCodeFieldInput: 'bg-background border border-border text-foreground',
    formResendCodeLink: 'text-primary hover:text-primary/80',
    alert: 'bg-muted border border-border',
    alertText: 'text-foreground',
    badge: 'bg-muted text-foreground',
    modalCloseButton: 'text-muted-foreground hover:text-foreground',
  },
};

export const userButtonAppearance = {
  baseTheme: dark,
  elements: {
    avatarBox: 'w-10 h-10',
    userButtonPopoverCard: 'bg-muted border border-border',
    userButtonPopoverText: 'text-foreground',
    userButtonPopoverFooter: 'hidden',
  },
};